server:
  port: 8081

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

spring:
  h2:
    console:
      enabled: true
    datasource:
      platform: h2
      url: 'jdbc:h2:mem:sam1'
      username: user
      password: pass
#  application:
#    name: ISSUES-SERVICE

  jpa:
    defer-datasource-initialization: 'true'

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true